package com.kp.monitor.basis.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kp.monitor.data.po.RecordFile;
import com.kp.monitor.data.po.User;

import com.kp.monitor.basis.db.RecordFileDao;
import com.kp.monitor.basis.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordFileDaoConfig;
    private final DaoConfig userDaoConfig;

    private final RecordFileDao recordFileDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordFileDaoConfig = daoConfigMap.get(RecordFileDao.class).clone();
        recordFileDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        recordFileDao = new RecordFileDao(recordFileDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(RecordFile.class, recordFileDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        recordFileDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public RecordFileDao getRecordFileDao() {
        return recordFileDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
